name: Hello World 

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]


jobs:
  hello-world :
    runs-on: ${{matrix.os}}
    steps:
    - name: List Files
        run: 
          pwd
          ls -a
    
    strategy:
      matrix:
       os: [ ubuntu-latest , windows-latest, macos-latest]
       

    steps:
    - uses: actions/checkout@v2
    - uses: ./test/
