name: Hello World 

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]


jobs:
  hello-world :
    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
